spring:
  application:
    name: demo

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update} # 'create'보다는 'update'가 기존 데이터를 유지하기에 안전합니다.
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false            # <--- 이 줄을 추가해서 경고를 해결했습니다!
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        highlight_sql: true        # SQL을 더 보기 좋게 컬러로 출력합니다.

security:
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 1800000        # 30분
  refresh-token-validity: 604800000     # 7일

server:
  port: 8081  # 이제 서버는 8081 포트에서 돌아갑니다.